### ISSUE TITLE
Document typo

### ISSUE THREAD

**Issue by pnwoodman** [Mattasher/probability-distributions#2]
On your site, under the negative binomal sample: http://statisticsblog.com/probability-distributions/#negativebinomial
The example uses the wrong function call:
PD.rbinom should be PD.rnbinom
This blocked me from using it properly for a while, so I would like to save someone else the same trouble :)

**Comment by Mattasher** [comment]
Thank you for catching this! I've fixed the issue. Sorry for the time you lost debugging!
