### ISSUE TITLE
Example code

### ISSUE THREAD

**Issue by apowers313** [Mattasher/probability-distributions#3]
The example code at http://statisticsblog.com/probability-distributions seems to be obfuscated -- it seems like all the work is being done in app.js, which appears to be minimized. Is app.js available somewhere?

**Comment by Mattasher** [comment]
Hi Adam I'm using webpack to "build" the page, which also minimizes it, as you note. It uses React JS under the hood. I'll consider putting the raw code into a public repo but it's entangled with lots of stuff so complicated. Meanwhile if there's something specific about that page's code you want to see I can post in here.

**Comment by apowers313** [comment]
Thanks!

Honestly, I was trying to figure out how to make some of the distributions provide integer results in a range [1,n] and I was going to steal your distribution graphing to make sure my algorithms didn't substantially alter the distributions. I think I've got it figured out now, but I still wouldn't mind knowing what you're using for graphing.

**Comment by Mattasher** [comment]
Here's the graphing libraries I used with the page:

`var histogram = require('histogramjs')`
`var ReactD3 = require('react-d3-components')`
`var BarChart = ReactD3.BarChart;`

**Comment by apowers313** [comment]
Thanks!
