### ISSUE TITLE
feature request: allow seeding of the PRNG

### ISSUE THREAD

**Issue by NodeGuy** [Mattasher/probability-distributions#4]
Thank you for creating this library!  For testing it's good to have deterministic randomness, e.g., https://github.com/davidbau/seedrandom.

**Comment by Mattasher** [comment]
Good suggestion! I'll get this in the next revision.

**Comment by Andu2** [comment]
Hello, is this package still being maintained? I've found it very useful. I, too, would like the ability to seed the random generation. I would create a pull request if I knew it would get looked at.
